/** Policy sections in the order the owner thinks about them; every policy field must belong to one (sections.test.ts). */
export const SECTION_ORDER = [
  'absence',
  'makeup',
  'closure',
  'billing',
  'dunning',
  'discount',
  'trial',
  'attendance',
  'calendar',
  'venue',
  'migration',
  'health',
  'consent',
  'regulations',
  'enrollment',
  'scheduling',
  'staffing',
  'payroll',
  'transport',
  'camp',
  'comms',
  'digest',
  'insights',
  'copilot',
] as const;
